### ISSUE TITLE
Question: are github1s and github.surf related in any way?

### ISSUE THREAD

**Issue by yousefamar** [conwnet/github1s#140]
See https://github.com/bridgedxyz/github.surf which sprung into existence 3 days ago and has been getting some traction, under a different license (Apache)

**Comment by yannbf** [comment]
I'm wondering the same. It seems like they copied this work and made a repo of their own. [Check this](https://github.com/bridgedxyz/github.surf/commit/67a365937699b088067a4bc9c85d7b6a90b17243#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L2).

I really hope this is related, otherwise that's not really nice, is it? 😄

**Comment by yousefamar** [comment]
Before bringing attention to this issue through my social media channels, I just saw [in the readme](https://github.com/bridgedxyz/github.surf#disclamer) that they say:

> this project is inspired from cdr/code-server and conwnet/github1s. the base code was forked from github1s (MIT License at the point of fork), which we are replacing it with our own implementations and approaches.

Not sure if it's technically legal to change the license like that, but either way it still kind of leaves a bad taste in my mouth. At the very least, they should actually fork the repo (such that it shows up as "forked from conwnet/github1s") rather than copy the codebase and commit to a brand new repo, misleading people into thinking this is an original Bridged project and totally their idea in "redefining user interface design". That disclaimer is very buried too, so I'm calling bad faith on this.

@bridgedxyz, @softmarshmallow, @GwonHeeJun, do you have anything to say about this?

**Comment by softmarshmallow** [comment]
> Before bringing attention to this issue through my social media channels, I just saw [in the readme](https://github.com/bridgedxyz/github.surf#disclamer) that they say:
> 
> > this project is inspired from cdr/code-server and conwnet/github1s. the base code was forked from github1s (MIT License at the point of fork), which we are replacing it with our own implementations and approaches.
> 
> Not sure if it's technically legal to change the license like that, but either way it still kind of leaves a bad taste in my mouth. At the very least, they should actually fork the repo (such that it shows up as "forked from conwnet/github1s") rather than copy the codebase and commit to a brand new repo, misleading people into thinking this is an original Bridged project and totally their idea in "redefining user interface design". That disclaimer is very buried too, so I'm calling bad faith on this.
> 
> @bridgedxyz, @softmarshmallow, @GwonHeeJun, do you have anything to say about this?

First of all, thanks for pointing this out.

We did not "fork" the project from github because github1s did't fork vscode either. (in our case we are using vscode as git submodule)
Our goal is to make a online editor with an remote compile feature included. And to bring best code surfing experience as you can infer from the name. that's why we are working on a chrome extensions and CLI experience on the most part. (and also support bitbucket and gitlab)

I understand this could be offended, but the whole point of the project is to make full experience of vscode in browser environment, and as noted on README we are focusing on server-side technologies to make the code buildable, executable, and ui-previewable.

Feel free to give us feedback. we can improve our README to reference github1s in a more highlighted way.

**Comment by yousefamar** [comment]
So your excuse for minimising @conwnet's contribution is "they did it first"? IMO even that is _very_ different — github1s is not trying to be VSCode, whereas github.surf being "inspired by" github1s is very much an understatement.

**Comment by softmarshmallow** [comment]
It takes time for us to actually fully-implement what we are trying to make. We are not trying to be github1s as github1s is not trying to be vscode.

**Comment by softmarshmallow** [comment]
Will this help?

https://github.com/bridgedxyz/github.surf/commit/1a858c22999e0a9d17fecae4e87b93b70086eece

**Comment by yousefamar** [comment]
You're missing the point, I'm not saying you shouldn't use @conwnet's code (after all, that's what OSS is all about, and the MIT license allows it, even for commercial use). What I'm saying is that it's a scumbag move to underplay their contribution. In @conwnet's extensions directory, they clearly have "This repo is forked from X" plastered at the very top. This tells me that they clearly weren't trying to pass off someone else's work as their own, but rather it's equivalent to using that code as a submodule/library. There is also no way that somebody could assume that github1s is affiliated with VSCode in anyway; the way they use VSCode's code is a technicality.

Meanwhile, people have every reason to believe that Brided _is_ trying to pass off @conwnet's work as their own. It doesn't matter if you transform it or add to it, it's clear you're still trying to minimise their contribution because "why should we if they haven't"?

**Comment by softmarshmallow** [comment]
Alright then, give us a phrase/text to indicate the contributors work. I'll put it, make it clear on the readme.

**Comment by yousefamar** [comment]
I don't think it's my place to tell you what to do, I think @conwnet should say that. Maybe @conwnet is actually totally ok with this. And I'm certainly not a lawyer, so I can't tell you if the Apache license is a problem.

What I can tell you is that this sentiment is not just unique to me. I mean, just look at the comments you got on ProductHunt: https://www.producthunt.com/posts/github-surf Nobody would have said these things if you had made it clear from the start

**Comment by softmarshmallow** [comment]
https://github.com/bridgedxyz/github.surf/commit/041cac5216d54e1bf58fcb7124ae0ab930af041e

Hope this solves your concern.

**Comment by justanotheranonymoususer** [comment]
@softmarshmallow imagine the following. You invest several months implementing Bitbucket support, compiling, and other features. Then I clone your code, publish it under "github.ninja", and give you that little credit buried somewhere at the bottom of the readme. All legal.

Then people see my "github.ninja" project and say: wow, so convenient, and it has both GitHub and Bitbucket support, and it's so fast, etc, etc. Well, of course, none of those will be thanks to my work, but people don't know that. Many people are familiar with VSCode, but not many are familiar with your project.

How would that make you feel?

And your comment from Product Hunt is just disrespectful:

> What does it bring that github1s does not?

> CLI, Gist, Jupyter support, other scms, and mostly, the cooler domain . surf

That's you basically saying: yeah, that guy did the actual work, but who cares, my project has a cooler name, which is way more important. And maybe it will have some other bells and whistles sometime in the future.

**Comment by softmarshmallow** [comment]
I am very sorry to upset you guys. I'll do my best to fix this. Just please know that the intentions were to make a surf tool with previewing features, linked to a private server (for computing resources)

Again, sincerely i apologize for this. i've clearly updated, pointed out that it's a fork from this repo, and also mentioned conwnet on the top of the readme

**Comment by gragib** [comment]
The quick and easy solution is to include this repo as a git submodule. You won't have to port changes manually. The other repo is licensed under Apache 2. IANAL, but you should be able to use MIT-licensed code in an AL2-licensed project.

**Comment by conwnet** [comment]
Thanks to everyone. I'm very happy that you like github1s. I love open source, it is my pleasure to contribute to the open source community.

github.surf is not related with github1s, although there is a little bit of unspeakable feel, I still don't blame anything. I also hope to learn something from github.surf to make github1s better.

In the days of from github1s release, I learned a lot from the contributors, this is my most precious harvest. we welcome the any contribution of all. And as you see, I'm not good at English, I also hope that you can help me improve the documentation.

github1s will be free forever, there won't even be any ads, I never intend to profit from it.

Because of the github pages, we needn't pay the web hosting bills. The only one bills is domain name, but compared to the user's approval (and a project may I can add to my resume), it is too cheap. It seems that some people are worried about the security of domain name, it hosted in Godaddy now, what should I do to dispel this worry?

**Comment by AlexBe1ov** [comment]
> It seems that some people are worried about the security of domain name, it hosted in Godaddy now, what should I do to dispel this worry?

In my opinion Godaddy has a bad reputation, maybe moving somewhere (namecheap?) is a good idea.

**Comment by shunia** [comment]
Note that most of the commits of that surf repo is like 'rename xxx'/'update readme'/'fix typo'.
In 5 days they did fantastic job on marketing by make a fancy readme, post on product hunt, write some medium blog posts, but not too much code changes, which means it's almost a copy and past job, with some marketing.
And all the info related to github1s is like some tiny shady words which says 'inspired' from actually direct copy past, and not even mentioned in the product hunt details.

I do admire their marketing job done out there but it feels really bad in tech community by copying a great open source project and rename it to there own and describe this as 'inspired by'.

What pops my head when I'm writing is 'Do they just copy-pasted some chrome/firefox extension code to make there own `official` extension?' Could be but didn't check it out though.

**Comment by kehao95** [comment]
I don't think it would be illegal to fork an MIT Licensed project and do your own 'implementations' and 'improvements'.  
People are angry for the way and time you are doing it. **This is not how open source works!**

### First of all: A Fork is a Fork
Sure you could have used the fork function which will keep all the git history rather than dumping all the source code with an "initialized" commit https://github.com/surfcodes/surf/commit/7d7c470afa5ff96a47dcbba35a869d215ad4ee08

### Respect the fxxking License!
MIT License is so permissive with only 20 lines ! Read it and don't break it!  

> Copyright conwnet and other contributors

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

How could you alter the copyright and remove the permission notice?
If you have to fork it, do it decently: [Fork MIT Licensed Project](https://gist.github.com/fbaierl/1d740a7925a6e0e608824eb27a429370)

Finally and most importantly:
### Respect how open source community works!
When a new open source project comes out, you like it and wants to make it better. Then you can create an issue, make suggestions and create PR if you can help. That's how we build open source projects with gathered intelligence. 
>  We are not trying to be github1s as github1s is not trying to be vscode.    

This might be a good excuse for forking future, but it's toooo dammit early. 
How can you assert what the project won't be within just few days it came out? I've already saw some issue talking about editing https://github.com/conwnet/github1s/issues/21

**Comment by ForsakenHarmony** [comment]
> p.s We'll take the repository down immediately if there is a legal issue of our action.

You can't release code written by someone else without having permission by everyone who contributed to it.
If a file was edited by 10 people and there's no CLA in place you need permission by all 10 to change its licence.

It's also a really shitty move to not include the original commits in your fork.

**Comment by shunia** [comment]
> What pops my head when I'm writing is 'Do they just copy-pasted some chrome/firefox extension code to make there own `official` extension?' Could be but didn't check it out though.

Oooook, I guess they do and I created an issue [here](https://github.com/surfcodes/surf/issues/27).

The official surf chrome extension code look totally alike to `Darkempire78/Github1s-Extension`, though it's just some simple codes.

lol.

**Comment by mmmeff** [comment]
The right thing for GithubSurf to do here, culturally, is to create an _actual_ fork in Github of the Github1s repository, make changes to drive functionality for their own product, and submit a pull request. Everyone wins.

**Comment by yassine-ah** [comment]
Wouldn't be better to consolidate the contributions of the both party to have a better solution ?  
if @softmarshmallow see that Github1s is missing something, then maybe a PR will be better than a fork ?! -- just thinking out loud
