### ISSUE TITLE
Question: Transfering data from window to extension

### ISSUE THREAD

**Issue by mecirmartin** [conwnet/github1s#292]
Hey, i have a question. 
I would like to use this implementation of vscode in browser as frontend for lowcode platform. I want to use this in iframe and i want to send data through window.postMessage.

However vscode extension has no access to window object. I tried creating custom command similarly to `github1s.vscode.get-browser-url` and i am able to register eventListener on window in this way, but i have no clue how to pass information from callback to extension

Is this even possible? 

Thanks for info

**Comment by conwnet** [comment]
> However vscode extension has no access to window object.

Yes, the extension runs inside a webworker, so we can't visit the `window` object directly. And the extension host service also runs inside an isolated iframe:

https://github.com/conwnet/github1s/blob/master/resources/index.html#L180-L181

We can also use the `postMessage` API inside a webworker (just contact with the extension host service directly), but I think the vscode command maybe better in this case.


> I tried creating custom command similarly to `github1s.vscode.get-browser-url` and i am able to register eventListener on window in this way, but i have no clue how to pass information from callback to extension

You can [register a command like `github1s.vscode.get-browser-url`](https://github.com/conwnet/github1s/blob/master/vscode-web-github1s/src/vs/code/browser/workbench/workbench.ts#L550) in vscode main service, and then the extension can get the data from vscode main service by using the extension API (`vscode.commands.executeCommand('github1s.vscode.get-browser-url', ...arguments)`). Noted the `Returns` of the `executeCommand` API is *the returned value of the given command*(the `window` object works here) and the `arguments` is the data we can get inside an extension context (webworker).

https://code.visualstudio.com/api/references/vscode-api#commands

You can also register a command inside an extension context using [the API (vscode.commands.registerCommand)](https://code.visualstudio.com/api/references/vscode-api#commands). So that we can call the function which comes from the extension context once the vscode is ready when we are in vscode main service.

Hope the information above can help you.

**Comment by mecirmartin** [comment]
Thanks for info

Still one piece of puzzle missing though. Next question is:
Is there any way to communicate between extension and main vscode service without using buttons and/or other user input?
I want to register RemoteFileSystem provider which will communicate with messages through window. The problem is that VsCode extension has no access to window. I tried tinkering with code in main service to register my provider there, but i ran into too much trouble, it's obvious that extension API is meant to be used to do this
So i tried registering commands and i'm able to receive commands and to run commands in extension and also in main service. The problem is that extension is not able to listen to executed commands
microsoft/vscode#1431 (comment)
and therefore i can't listen to events that are occuring outside extension (events comming from window)

Is there any way to achieve bidirectional communication between main window and extension?

**Comment by mecirmartin** [comment]
Thank you very much this was helpful
