### ISSUE TITLE
是否有可能接入"stackblitz / core"以实现在线终端功能?

### ISSUE THREAD

**Issue by 643104191** [conwnet/github1s#318]
参考:https://stackblitz.com/

**Comment by conwnet** [comment]
感谢建议，

我觉得接入终端也很难支持在线运行代码（因为目前我们没有下载全部代码，只是当用户打开文件时获取相应的内容），并且这也只支持 JavaScript.

在浏览器上运行 Node.js 这个能力我更想用来支持安装绝大多数 VSCode Extension...

Thanks for your suggestion,

I think it's difficult for running code online with it (because we don't download all the codes of a repository at present, we just get the corresponding content when the user opens the file), and it only supports JavaScript now.

Running node.js on the browser is really cool, I prefer to use it to support the installation of most vscode extensions...

**Comment by conwnet** [comment]
related #314
