### ISSUE TITLE
How to build @github1s/vscode-web

### ISSUE THREAD

**Issue by naivenaive** [conwnet/github1s#415]
Thanks for your excellent work. I have successfully built github1s locally. I wish to edit the workbench and rebuild a similar version of vscode like @github1s/vscode-web. Would you please kindly share the code to build @github1s/vscode-web or give me some advice on how to build @github1s/vscode-web from original [vscode](https://github.com/microsoft/vscode)? Many thanks.

**Comment by conwnet** [comment]
1. In order to build `vscode-web` you can run `yarn build:vscode`, then you will get the target files in `vscode-web/dist`
2. you can also run github1s with `dev vscode mode`, the command is `yarn watch-with-vscode`. (This command may need several minutes to prepare vscode, so you won't see github1s until the preparation complete)
