### ISSUE TITLE
Window closed when typing CTRL+W

### ISSUE THREAD

**Issue by mredigonda** [conwnet/github1s#43]
The default behavior from VSCode when you type CTRL+W is certainly to close the tab, not the entire IDE, and I'm used to using that combination. When used in `github1s` sites though, the window is closed (sure a warning is showed first, but after the first try the window gets closed).

It would avoid some frustration if CTRL+W closed tabs instead of the actual chrome tab, there may be reasons these can't be done though, but just pointing it out here.

Awesome project.

**Comment by GriceTurrble** [comment]
This project is basically wrapping VS Code's in-browser editor experience, so it's beholden to the constraints there. Same applies to GitHub Codespaces, in fact.

In all cases, the VS Code in-browser editor uses `Ctrl-F4` to close tabs instead of `Ctrl-W`. And I don't think that's optional: likely the browser captures `Ctrl-W` before the editor can try to handle that event.

**Comment by Siddhant-K-code** [comment]
Yes, Even in other Online IDEs like Repl.it also doesn't support that `Ctrl - w` because the browser captures it first than other websites and all?

**Comment by JammSpread** [comment]
This can be worked around by installing `GitHub 1s` as a shortcut or PWA.
However also the functionality of `CTRL + W` can be disabled via a call to `event.preventDefault`.

**Comment by JammSpread** [comment]
Also this doesn't occur when in GitHub1s' fullscreen mode.
