### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by ghandic** [conwnet/github1s#57]
Any chance you guys are adding support for other browsers?

**Comment by kiprasmel** [comment]
I think adding a browser polyfill [1] and using the `browser` variable instead of `chrome` would be enough since this is such a simple extension.

But I don't like that it is **not** open source **and** has a privacy policy [2] -- I am not going to use it personally, might as well create my own and open source it:D

[1] https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension#The_WebExtension_browser_API_Polyfill

[2] https://chrome.google.com/webstore/detail/github1s/lodjfmkfbfkpdhnhkcdcoonghhghbkhe/

**Comment by xcv58** [comment]
There is one firefox extension https://github.com/Darkempire78/Github1s-Extension

Please file the request issue to the related extension repo if needed.
